FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir pandas numpy plotly streamlit psycopg2-binary sqlalchemy python-dotenv
COPY dashboard/ ./dashboard/
EXPOSE 8501
CMD ["streamlit", "run", "dashboard/app.py", "--server.address=0.0.0.0"]